# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfbd903a375b85af256b93bf7f4e0af466b508732afadc51b703dbab5f23094b4311c60f405cf1b4c2c10b7dc588acb63628ff8fa5730195de2862f6b72f6332

test:
  secret_key_base: 4b5a4afc8b4535d134bdd383358fac158b90f3e238b2e6dd496e01cd87d40d3ec12a7d77211f1b5e5c77b1c5ec2d80500b5514ba94251267007f19574feef66a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
